[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"


[dependencies]
indexmap = "2.1.0"
rayon = "1.8.0"
regex = "1.10.2"
# colored = "2.0.4"
# itertools = "0.10.0"
# tracing = "0.1.40"
# tracing-subscriber = "0.3.18"
# thiserror = "1.0.50"
